# Generated by Django 5.2.1 on 2025-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrequest',
            name='job_applications',
            field=models.ManyToManyField(to='jobs.jobapplication'),
        ),
    ]
