# Generated by Django 5.2.1 on 2025-05-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_companyrequest_job_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrequest',
            name='job_applications',
        ),
    ]
