# Generated by Django 5.2.1 on 2025-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0003_visitinglog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitinglog',
            old_name='timestamp',
            new_name='visit_time',
        ),
        migrations.RemoveField(
            model_name='visitinglog',
            name='ip_adress',
        ),
        migrations.AddField(
            model_name='visitinglog',
            name='ip_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitinglog',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitinglog',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitinglog',
            name='user_agent',
            field=models.CharField(max_length=200),
        ),
    ]
