# Generated by Django 5.2 on 2025-11-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0003_newsen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'خبر', 'verbose_name_plural': 'الأخبار'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='خبر مثبت'),
        ),
    ]
