# Generated by Django 5.2 on 2025-11-06 05:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0004_alter_news_options_news_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsen',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='newsen',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned Article'),
        ),
        migrations.AlterField(
            model_name='newsen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='newsen',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='newsen',
            name='paragraph',
            field=models.TextField(verbose_name='Article Content'),
        ),
        migrations.AlterField(
            model_name='newsen',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Article Title'),
        ),
    ]
