# Generated by Django 5.2.1 on 2025-05-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0004_rename_timestamp_visitinglog_visit_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitinglog',
        ),
    ]
